# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "pata_jmicron" "sata_sil" "usbhid" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e53a8b2b-2168-422c-87ed-8628dabe779a";
      fsType = "btrfs";
    };

  fileSystems."/media/btrfs-data" =
    { device = "/dev/sdc";
      fsType = "btrfs";
    };

  fileSystems."/media/movies" =
    { device = "/dev/sdc";
      fsType = "btrfs";
      options = [ "subvol=@movies" ];
    };

  fileSystems."/home" =
    { device = "/dev/sdc";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/55a1f780-8ba7-4dcd-a45e-f6537d80f94a"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
}
