# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e53a8b2b-2168-422c-87ed-8628dabe779a";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A1FD-E989";
      fsType = "vfat";
    };

  fileSystems."/media/btrfs-data" =
    { device = "/dev/disk/by-uuid/8b1736a0-5b11-4b0a-819a-4b76e325cc7b";
      fsType = "btrfs";
    };

  fileSystems."/media/movies" =
    { device = "/dev/disk/by-uuid/8b1736a0-5b11-4b0a-819a-4b76e325cc7b";
      fsType = "btrfs";
      options = [ "subvol=@movies" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/8b1736a0-5b11-4b0a-819a-4b76e325cc7b";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/04abcec5-13da-4740-9113-9a4eaa71b0ac"; }
    ];

  nix.settings.max-jobs = lib.mkDefault 16;
}
